### ISSUE TITLE
PDF Problems

### ISSUE THREAD

**Issue by mmsa** [Geexbee/RiskToolFX#1]
![screenshot 2017-03-24 11 02 13](https://cloud.githubusercontent.com/assets/6832796/24291566/60bf7572-1081-11e7-89b6-eb029c68882d.png)

- Overlaying the table and the pie chart
- Icons scaled up

**Comment by StereoRocker** [comment]
Fixed in [Commit #75185a0](https://github.com/Geexbee/RiskToolFX/commit/75185a098f1cf0111f7bfaa7e041a07d13c7d465)
