### ISSUE TITLE
Adding chemical to the dataset

### ISSUE THREAD

**Issue by mmsa** [Geexbee/RiskToolFX#3]
I received an error instead of error message to the user

![screenshot 2017-03-24 11 04 33](https://cloud.githubusercontent.com/assets/6832796/24291669/d23620fc-1081-11e7-9799-1a64f0edf9d3.png)

**Comment by StereoRocker** [comment]
Fixed with [Commit #ae6b28d](https://github.com/Geexbee/RiskToolFX/commit/ae6b28dc83d297073d2a4dff9088f0b97e099584)
